/**
 * MATLAB®/Octave like syntax parser/interpreter/compiler.
 */

import Parser from './parser.js';
import { constantsTable } from './constants-table';
import { substGreek } from './subst-greek';
import { CharString } from './char-string';
import { ComplexDecimal } from './complex-decimal';
import { MultiArray } from './multi-array';
import { Tensor } from './tensor';

/**
 * aliasNameTable type.
 */
export type TAliasNameTable = Record<string, RegExp>;

/**
 * baseFunctionTable type.
 */
export type TBaseFunctionTableEntry = {
    mapper?: boolean;
    ev: boolean[];
    func: Function;
};
export type TBaseFunctionTable = Record<string,TBaseFunctionTableEntry>;

/**
 * nameTable type.
 */
export type TNameTableEntry = {
    args: Array<any>;
    expr: any
};
export type TNameTable = Record<string,TNameTableEntry>;

/**
 * commandWordListTable type.
 */
export type TCommandWordListFunction = (...args: string[]) => void;
export type TCommandWordListTableEntry = {
    func: TCommandWordListFunction;
};
export type TCommandWordListTable = Record<string,TCommandWordListTableEntry>;

/**
 * TEvaluatorConfig type.
 */
export type TEvaluatorConfig = {
    aliasTable?: TAliasNameTable;
    externalFunctionTable?: TBaseFunctionTable;
    externalCmdWListTable?: TCommandWordListTable;
};

/**
 * AST (Abstract Syntax Tree) nodes.
 */

/**
 * Expression node.
 */
export type NodeExpr = NodeName | NodeArgExpr | NodeOperation | NodeList;

/**
 * Range node.
 */
interface NodeRange {
    start: NodeExpr | null;
    stop: NodeExpr | null;
    stride: NodeExpr | null;
}

/**
 * Common primary node.
 */
interface PrimaryNode {
    type: string | number;
}

/**
 * Reserved node.
 */
interface NodeReserved extends PrimaryNode {}

/**
 * Name node.
 */
export interface NodeName extends PrimaryNode {
    type: 'NAME';
    id: string;
}

/**
 * Command word list node.
 */
interface NodeCmdWList extends PrimaryNode {
    type: 'CmdWList';
    id: string;
    args: Array<CharString>;
}

/**
 * Expression and arguments node.
 */
export interface NodeArgExpr extends PrimaryNode {
    type: 'ARG';
    expr: NodeExpr;
    args: Array<NodeExpr>;
}

/**
 * Operation node.
 */
export type NodeOperation = UnaryOperation | BinaryOperation;

/**
 * Unary operation node.
 */
type UnaryOperation = UnaryOperationL | UnaryOperationR;

/**
 * Right unary operation node.
 */
interface UnaryOperationR extends PrimaryNode {
    right: NodeExpr;
}

/**
 * Left unary operation node.
 */
interface UnaryOperationL extends PrimaryNode {
    left: NodeExpr;
}

/**
 * Binary operation.
 */
interface BinaryOperation extends PrimaryNode {
    left: NodeExpr;
    right: NodeExpr;
}

/**
 * List node
 */
export interface NodeList {
    list: Array<NodeExpr>;
}

/**
 * External parser declarations (defined in parser body)
 */
declare global {
    /* eslint-disable-next-line  no-var */
    var EvaluatorPointer: Evaluator;
    /* eslint-disable-next-line  no-var */
    var commandsTable: string[];
}

/**
 * Evaluator object
 * It is implemented as a class but cannot be instantiated more than one time
 * simultaneously. Instance is given by `Evaluator.initialize` static method.
 */
export class Evaluator {
    /**
     * After run Parser or Evaluate method, the exitStatus property will contains
     * exit state of method.
     */
    public static response = {
        EXTERNAL: -2,
        WARNING: -1,
        OK: 0,
        LEX_ERROR: 1,
        PARSER_ERROR: 2,
        EVAL_ERROR: 3,
    };

    /**
     * Debug flag, setter and getter.
     */
    private _debug: boolean = false;

    public get debug(): boolean {
        return this._debug;
    }

    public set debug(value: boolean) {
        this._debug = value;
    }

    /**
     * Native name table. It's inserted in nameTable when
     * `Evaluator.initialize` executed.
     */
    private readonly nativeNameTable: Record<string,ComplexDecimal> = {
        false: ComplexDecimal.false(),
        true: ComplexDecimal.true(),
        i: ComplexDecimal.onei(),
        I: ComplexDecimal.onei(),
        j: ComplexDecimal.onei(),
        J: ComplexDecimal.onei(),
        e: ComplexDecimal.e(),
        pi: ComplexDecimal.pi(),
        inf: ComplexDecimal.inf_0(),
        Inf: ComplexDecimal.inf_0(),
        NaN: ComplexDecimal.NaN_0(),
    };

    /**
     * Name table.
     */
    public nameTable: TNameTable = {};

    public readonlyNameTable: string[] = [];

    /**
     * Alias table.
     */
    private aliasTable: TAliasNameTable;

    /**
     * Base function table.
     */
    public baseFunctionTable: TBaseFunctionTable = {};

    public get baseFunctionList(): string[] {
        return Object.keys(this.baseFunctionTable);
    }

    /**
     * Local table.
     */
    public localTable: Record<string,any> = {};

    /**
     * Command word list table.
     */
    public commandWordListTable: TCommandWordListTable = {};

    /**
     * Parser (generated by Jison).
     */
    private readonly parser: { parse: (input: string) => any } = Parser;

    /**
     * Evaluator exit status.
     */
    public exitStatus: number = Evaluator.response.OK;

    private incDecOp(pre: boolean, operation: 'plus' | 'minus'): (tree: any) => any {
        if (pre) {
            return (tree: any): any => {
                if (tree.type === 'NAME') {
                    if (this.nameTable[tree.id].expr) {
                        this.nameTable[tree.id].expr = Tensor[operation](this.nameTable[tree.id].expr, ComplexDecimal.one());
                        return this.nameTable[tree.id].expr;
                    } else {
                        throw new Error('in x++ or ++x, x must be defined first.');
                    }
                } else {
                    throw new SyntaxError(`invalid ${operation === 'plus' ? 'increment' : 'decrement'} variable.`);
                }
            };
        } else {
            return (tree: any): any => {
                if (tree.type === 'NAME') {
                    if (this.nameTable[tree.id].expr) {
                        const value = Tensor.copy(this.nameTable[tree.id].expr);
                        this.nameTable[tree.id].expr = Tensor[operation](this.nameTable[tree.id].expr, ComplexDecimal.one());
                        return value;
                    } else {
                        throw new Error('in x++ or ++x, x must be defined first.');
                    }
                } else {
                    throw new SyntaxError(`invalid ${operation === 'plus' ? 'increment' : 'decrement'} variable.`);
                }
            };
        }
    }

    /**
     * Operator table.
     */
    private readonly opTable: Record<string,Function> = {
        '+': Tensor.plus,
        '-': Tensor.minus,
        '.*': Tensor.times,
        '*': Tensor.mtimes,
        './': Tensor.rdivide,
        '/': Tensor.mrdivide,
        '.\\': Tensor.ldivide,
        '\\': Tensor.mldivide,
        '.^': Tensor.power,
        '^': Tensor.mpower,
        '+_': Tensor.uplus,
        '-_': Tensor.uminus,
        ".'": Tensor.transpose,
        "'": Tensor.ctranspose,
        '<': Tensor.lt,
        '<=': Tensor.le,
        '==': Tensor.eq,
        '>=': Tensor.ge,
        '>': Tensor.gt,
        '!=': Tensor.ne,
        '&': Tensor.and,
        '|': Tensor.or,
        '!': Tensor.not,
        '&&': Tensor.mand,
        '||': Tensor.mor,
        '++_': this.incDecOp(true, 'plus'),
        '--_': this.incDecOp(true, 'minus'),
        '_++': this.incDecOp(false, 'plus'),
        '_--': this.incDecOp(false, 'minus'),
    };

    public get opList(): string[] {
        return Object.keys(this.opTable);
    }

    /**
     * Parser AST (Abstract Syntax Tree) constructor methods.
     */

    public readonly nodeString = CharString.parse;
    public readonly isString = CharString.isThis;
    public readonly unparseString = CharString.unparse;
    public readonly unparseStringML = CharString.unparseML;
    public readonly removeQuotes = CharString.removeQuotes;
    public readonly nodeNumber = ComplexDecimal.parse;
    public readonly newNumber = ComplexDecimal.newThis;
    public readonly isNumber = ComplexDecimal.isThis;
    public readonly unparseNumber = ComplexDecimal.unparse;
    public readonly unparseNumberML = ComplexDecimal.unparseML;
    public readonly isTensor = MultiArray.isThis;
    public readonly isRange = MultiArray.isRange;
    public readonly unparseTensor = MultiArray.unparse;
    public readonly unparseTensorML = MultiArray.unparseML;
    public readonly evaluateTensor = MultiArray.evaluate;
    public readonly mapTensor = MultiArray.map;
    public readonly getItems = MultiArray.getItems;
    public readonly expandRange = MultiArray.expandRange;
    public readonly firstRow = MultiArray.firstRow;
    public readonly appendRow = MultiArray.appendRow;
    public readonly tensor0x0 = MultiArray.mat_0x0;

    public readonly linearize = MultiArray.linearize;

    /**
     * Evaluator object constructor
     */
    private constructor() {
        global.EvaluatorPointer = this;
        this.exitStatus = Evaluator.response.OK;
        /* Set opTable aliases */
        this.opTable['**'] = this.opTable['^'];
        this.opTable['.**'] = this.opTable['.^'];
        this.opTable['~='] = this.opTable['!='];
        this.opTable['~'] = this.opTable['!'];
        /* Load nativeNameTable and constantsTable in nameTable */
        this.loadNativeTable();
        /* Define function operators */
        for (const func in Tensor.twoMoreOpFunction) {
            this.DefBinMoreOpFunction(func, Tensor.twoMoreOpFunction[func]);
        }
        for (const func in Tensor.binaryOpFunction) {
            this.DefBinOpFunction(func, Tensor.binaryOpFunction[func]);
        }
        for (const func in Tensor.unaryOpFunction) {
            this.DefUnOpFunction(func, Tensor.unaryOpFunction[func]);
        }
        /* Define function mappers */
        for (const func in ComplexDecimal.mapFunction) {
            this.defFunction(func, ComplexDecimal.mapFunction[func], true);
        }
        /* Define other functions */
        for (const func in ComplexDecimal.twoArgFunction) {
            this.defFunction(func, ComplexDecimal.twoArgFunction[func]);
        }
        for (const func in MultiArray.functions) {
            this.defFunction(func, MultiArray.functions[func]);
        }
        for (const func in MultiArray.linearizedFunctions) {
            this.DefLinearizedFunction(func, MultiArray.linearizedFunctions[func].func, MultiArray.linearizedFunctions[func].lin);
        }
    }

    /**
     * Evaluator initialization.
     * @param config Evaluator configuration.
     * @returns Evaluator instance.
     */
    public static initialize(config?: TEvaluatorConfig): Evaluator {
        const evaluator = new Evaluator();
        if (config) {
            if (config.aliasTable) {
                evaluator.aliasTable = config.aliasTable;
                evaluator.aliasName = (name: string): string => {
                    let result = false;
                    let aliasname = '';
                    for (const i in evaluator.aliasTable) {
                        if (evaluator.aliasTable[i].test(name)) {
                            result = true;
                            aliasname = i;
                            break;
                        }
                    }
                    if (result) {
                        return aliasname;
                    } else {
                        return name;
                    }
                };
            } else {
                evaluator.aliasName = (name: string): string => name;
            }
            if (config.externalFunctionTable) {
                Object.assign(evaluator.baseFunctionTable, config.externalFunctionTable);
            }
            if (config.externalCmdWListTable) {
                Object.assign(evaluator.commandWordListTable, config.externalCmdWListTable);
            }
            for (const cmd in evaluator.commandWordListTable) {
                global.commandsTable.push(cmd);
            }
        } else {
            evaluator.aliasName = (name: string): string => name;
        }
        return evaluator;
    }

    /**
     * Alias name function.
     * @param name
     * @returns
     */
    public aliasName: (name: string) => string = (name: string): string => name;

    /**
     * Load native name table in name table.
     */
    private loadNativeTable(): void {
        /* Insert nativeNameTable in nameTable */
        for (const name in this.nativeNameTable) {
            this.nameTable[name] = { args: [], expr: this.nativeNameTable[name] };
            this.readonlyNameTable.push(name);
        }
        /* Insert constantsTable in nameTable */
        for (const name in constantsTable) {
            this.nameTable[constantsTable[name][0]] = { args: [], expr: constantsTable[name][1] };
            this.readonlyNameTable.push(constantsTable[name][0]);
        }
    }

    /**
     * Restart evaluator.
     */
    public Restart(): void {
        this.nameTable = {};
        this.localTable = {};
        this.readonlyNameTable = [];
        this.loadNativeTable();
    }

    /**
     * Parse input.
     * @param input
     * @returns
     */
    public Parse(input: string): any {
        return this.parser.parse(input);
    }

    /**
     * Create reserved node.
     * @param nodeid
     * @returns
     */
    public nodeReserved(nodeid: string): NodeReserved {
        return { type: nodeid };
    }

    /**
     * Create name node.
     * @param nodeid
     * @returns
     */
    public nodeName(nodeid: string): NodeName {
        return { type: 'NAME', id: nodeid.replace(/(\r\n|[\n\r])|[\ ]/gm, '') };
    }

    /**
     * Create command word list node.
     * @param nodename
     * @param nodelist
     * @returns
     */
    public nodeCmdWList(nodename: NodeName, nodelist: NodeList): NodeCmdWList {
        return { type: 'CmdWList', id: nodename.id, args: nodelist ? (nodelist.list as any) : [] };
    }

    /**
     * Create expression and arguments node.
     * @param nodeexpr
     * @param nodelist
     * @returns
     */
    public nodeArgExpr(nodeexpr: any, nodelist?: any): NodeArgExpr {
        return { type: 'ARG', expr: nodeexpr, args: nodelist ? nodelist.list : [] };
    }

    /**
     * Create range node.
     * @param left
     * @param right
     * @returns
     */
    public nodeRange(left: any, ...right: any): NodeRange {
        /* https://www.mathworks.com/help/matlab/ref/end.html */
        if (right.length === 1) {
            return { start: left, stop: right[0], stride: null };
        } else if (right.length === 2) {
            return { start: left, stop: right[1], stride: right[0] };
        } else {
            throw new Error('invalid range.');
        }
    }

    /**
     * Create operator node.
     * @param op
     * @param data1
     * @param data2
     * @returns
     */
    public nodeOp(op: string, data1: any, data2: any): NodeOperation {
        switch (op) {
            case '+':
            case '-':
            case '.*':
            case '*':
            case './':
            case '/':
            case '.\\':
            case '\\':
            case '.^':
            case '^':
            case '.**':
            case '**':
            case '<':
            case '<=':
            case '==':
            case '>=':
            case '>':
            case '!=':
            case '~=':
            case '&':
            case '|':
            case '&&':
            case '||':
            case '=':
            case '+=':
            case '-=':
            case '*=':
            case '/=':
            case '\\=':
            case '^=':
            case '**=':
            case '.*=':
            case './=':
            case '.\\=':
            case '.^=':
            case '.**=':
            case '&=':
            case '|=':
                return { type: op, left: data1, right: data2 };
            case '()':
            case '!':
            case '~':
            case '+_':
            case '-_':
            case '++_':
            case '--_':
                return { type: op, right: data1 };
            case ".'":
            case "'":
            case '_++':
            case '_--':
                return { type: op, left: data1 };
            default:
                return { type: 'INVALID' } as NodeOperation;
        }
    }

    /**
     * Create first element of list node.
     * @param node
     * @returns
     */
    public nodeListFirst(node?: any): NodeList {
        if (node) {
            return { list: [node] };
        } else {
            return { list: [] };
        }
    }

    /**
     * Append node to list node.
     * @param lnode
     * @param node
     * @returns
     */
    public nodeList(lnode: any, node: any): NodeList {
        lnode.list.push(node);
        return lnode;
    }

    /**
     * Create first row of a matrix MultiArray.
     * @param row
     * @returns
     */
    public nodeFirstRow(row: any): MultiArray {
        if (row) {
            return this.firstRow(row.list);
        } else {
            return this.tensor0x0();
        }
    }

    /**
     * Append row to matrix MultiArray.
     * @param matrix
     * @param row
     * @returns
     */
    public nodeAppendRow(matrix: any, row: any): MultiArray {
        if (row) {
            return this.appendRow(matrix, row.list);
        } else {
            return matrix;
        }
    }

    /**
     * Validate left hand side of assignment node.
     * @param tree
     * @returns
     */
    public validateAssignment(tree: any): any {
        const invalidMessage = 'invalid left hand side of assignment';
        if (tree.type === 'NAME') {
            if (this.readonlyNameTable.includes(tree.id)) {
                throw new Error(`${invalidMessage}: cannot assign to a read only value: ${tree.id}.`);
            }
            return tree;
        } else if (tree.type === 'ARG' && tree.expr.type === 'NAME') {
            if (this.readonlyNameTable.includes(tree.expr.id)) {
                throw new Error(`${invalidMessage}: cannot assign to a read only value: ${tree.expr.id}.`);
            }
            return tree;
        } else {
            throw new Error(`${invalidMessage}.`);
        }
    }

    /**
     * Define function in baseFunctionTable.
     * @param name
     * @param func
     * @param map
     */
    private defFunction(name: string, func: Function, map?: boolean, ev?: boolean[]): void {
        this.baseFunctionTable[name] = {
            mapper: map ?? false,
            ev: ev ?? [],
            func,
        };
    }

    /**
     * Define unary operator function in baseFunctionTable.
     * @param name
     * @param func
     */
    private DefUnOpFunction(name: string, func: Function): void {
        this.baseFunctionTable[name] = {
            mapper: false,
            ev: [],
            func: (...operand: any) => {
                if (operand.length === 1) {
                    return func(operand[0]);
                } else {
                    throw new Error(`Invalid call to ${name}.`);
                }
            },
        };
    }

    /**
     * Define binary operator function in baseFunctionTable.
     * @param name
     * @param func
     */
    private DefBinOpFunction(name: string, func: Function): void {
        this.baseFunctionTable[name] = {
            mapper: false,
            ev: [],
            func: (left: any, ...right: any) => {
                if (right.length === 1) {
                    return func(left, right[0]);
                } else {
                    throw new Error(`Invalid call to ${name}.`);
                }
            },
        };
    }

    /**
     * Define define two-or-more operator function in baseFunctionTable.
     * @param name
     * @param func
     */
    private DefBinMoreOpFunction(name: string, func: Function): void {
        this.baseFunctionTable[name] = {
            mapper: false,
            ev: [],
            func: (left: any, ...right: any) => {
                if (right.length === 1) {
                    return func(left, right[0]);
                } else if (right.length > 1) {
                    let result = func(left, right[0]);
                    for (let i = 1; i < right.length; i++) {
                        result = func(result, right[i]);
                    }
                    return result;
                } else {
                    throw new Error(`Invalid call to ${name}.`);
                }
            },
        };
    }

    /**
     * Define function with matrix linearization.
     * @param name Function name.
     * @param func Function body.
     * @param linearize boolean[ ] indicating wich argument is linearized.
     */
    private DefLinearizedFunction(name: string, func: Function, linearize: boolean[]): void {
        this.baseFunctionTable[name] = {
            mapper: false,
            ev: linearize,
            func: (...args: any[]) => {
                args.forEach((value, index) => {
                    if (linearize[index]) {
                        if ('array' in value) {
                            args[index] = this.linearize(args[index]);
                        }
                    }
                });
                return func(...args);
            },
        };
    }

    /**
     * Expression tree recursive evaluator.
     * @param tree
     * @param local
     * @param fname
     * @returns
     */
    public Evaluator(tree: any, local: boolean, fname: string): any {
        let aliasTreeName: string;
        if (this.debug) {
            console.log(`Evaluator(\ntree:${JSON.stringify(tree, null, 2)},\nlocal:${local},\nfname:${fname})`);
        }
        if ('list' in tree) {
            const result = { list: new Array(tree.list.length) };
            for (let i = 0; i < tree.list.length; i++) {
                /* Convert undefined name, defined in word-list command, to word-list command.
                 * (Null length word-list command) */
                if (
                    tree.list[i].type === 'NAME' &&
                    !(local && this.localTable[fname] && this.localTable[fname][tree.list[i].id]) &&
                    !(tree.list[i].id in this.nameTable) &&
                    commandsTable.indexOf(tree.list[i].id) >= 0
                ) {
                    tree.list[i].type = 'CmdWList';
                    tree.list[i]['args'] = [];
                }
                result.list[i] = this.Evaluator(tree.list[i], local, fname);
                if (typeof result.list[i].type === 'number') {
                    this.nameTable['ans'] = { args: [], expr: result.list[i] };
                }
            }
            return result;
        } else if (this.isNumber(tree) || this.isString(tree)) {
            /* NUMBER or STRING */
            return tree;
        } else if (this.isTensor(tree)) {
            /* MATRIX */
            return this.evaluateTensor(tree, this, fname);
        } else if (this.isRange(tree)) {
            /* RANGE */
            return this.expandRange(
                this.Evaluator(tree.start, local, fname),
                this.Evaluator(tree.stop, local, fname),
                tree.stride ? this.Evaluator(tree.stride, local, fname) : null,
            );
        } else {
            switch (tree.type) {
                case '+':
                case '-':
                case '.*':
                case '*':
                case './':
                case '/':
                case '.\\':
                case '\\':
                case '.^':
                case '^':
                case '.**':
                case '**':
                case '<':
                case '<=':
                case '==':
                case '>=':
                case '>':
                case '!=':
                case '~=':
                case '&':
                case '|':
                case '&&':
                case '||':
                    return this.opTable[tree.type](this.Evaluator(tree.left, local, fname), this.Evaluator(tree.right, local, fname));
                case '()':
                    return this.Evaluator(tree.right, local, fname);
                case '+_':
                case '-_':
                    return this.opTable[tree.type](this.Evaluator(tree.right, local, fname));
                case '++_':
                case '--_':
                    return this.opTable[tree.type](tree.right);
                case ".'":
                case "'":
                    return this.opTable[tree.type](this.Evaluator(tree.left, local, fname));
                case '_++':
                case '_--':
                    return this.opTable[tree.type](tree.left);
                case '=':
                case '+=':
                case '-=':
                case '*=':
                case '/=':
                case '\\=':
                case '^=':
                case '**=':
                case '.*=':
                case './=':
                case '.\\=':
                case '.^=':
                case '.**=':
                case '&=':
                case '|=':
                    this.validateAssignment(tree.left);
                    const op: string = tree.type.substring(0, tree.type.length - 1);
                    let left;
                    let id;
                    let args;
                    if (tree.left.type === 'NAME') {
                        left = tree.left;
                        id = tree.left.id;
                        aliasTreeName = this.aliasName(tree.left.id);
                        args = [];
                    } else {
                        /* (tree.left.type==='ARG') && (tree.left.expr.type==='NAME') */
                        left = tree.left.expr;
                        id = tree.left.expr.id;
                        aliasTreeName = this.aliasName(tree.left.expr.id);
                        args = tree.left.args;
                    }
                    if (aliasTreeName in this.baseFunctionTable) {
                        throw new Error(`cannot assign to reserved name: ${aliasTreeName}.`);
                    } else {
                        if (args.length === 0) {
                            /* Name definition */
                            const expr = op.length ? this.nodeOp(op, left, tree.right) : tree.right;
                            try {
                                this.nameTable[id] = { args: [], expr: this.Evaluator(expr, false, fname) };
                                return this.nodeOp('=', left, this.nameTable[id].expr);
                            } catch (e) {
                                this.nameTable[id] = { args: [], expr: expr };
                                throw e;
                            }
                        } else {
                            if (this.nameTable[id] && this.isTensor(this.nameTable[id].expr)) {
                                /* Matrix indexing refer */
                                console.log('matrix indexing refer at left hand side');
                                return tree; /** */
                            } else {
                                /* Function definition. Test if args is a list of NAME */
                                let pass = true;
                                for (let i = 0; i < args.length; i++) {
                                    pass = pass && args[i].type === 'NAME';
                                    if (!pass) throw new Error('invalid arguments in function definition.');
                                }
                                this.nameTable[id] = { args: args, expr: tree.right };
                                return tree;
                            }
                        }
                    }
                    break;
                case 'NAME':
                    if (local && this.localTable[fname] && this.localTable[fname][tree.id]) {
                        /* Defined in localTable */
                        return this.localTable[fname][tree.id];
                    } else if (tree.id in this.nameTable) {
                        /* Defined in nameTable */
                        if (this.nameTable[tree.id].args.length === 0) {
                            /* Defined as name */
                            return this.Evaluator(this.nameTable[tree.id].expr, false, fname);
                        } else {
                            /* Defined as function name */
                            throw new SyntaxError(`calling ${tree.id} function without arguments list.`);
                        }
                    }
                case 'ARG':
                    const argumentsList: any[] = [];
                    if (tree.expr.type === 'NAME') {
                        /* Matrix indexing or function call */
                        aliasTreeName = this.aliasName(tree.expr.id);
                        if (aliasTreeName in this.baseFunctionTable) {
                            /* Is base function */
                            if (typeof this.baseFunctionTable[aliasTreeName]['mapper'] !== 'undefined') {
                                /* arguments evaluated */
                                for (let i = 0; i < tree.args.length; i++) {
                                    /* Evaluate arguments list */
                                    argumentsList[i] = this.Evaluator(tree.args[i], local, fname);
                                }
                                if (this.baseFunctionTable[aliasTreeName].mapper && argumentsList.length !== 1) {
                                    /* Error if mapper and #arguments!==1 (Invalid call) */
                                    throw new Error(`Invalid call to ${aliasTreeName}.`);
                                }
                                if (argumentsList.length === 1 && 'array' in argumentsList[0] && this.baseFunctionTable[aliasTreeName].mapper) {
                                    /* Test if is mapper */
                                    return this.mapTensor(argumentsList[0], this.baseFunctionTable[aliasTreeName].func);
                                } else {
                                    return this.baseFunctionTable[aliasTreeName].func(...argumentsList);
                                }
                            } else {
                                /* arguments selectively evaluated */
                                for (let i = 0; i < tree.args.length; i++) {
                                    /* Evaluate arguments list selectively */
                                    argumentsList[i] = (this.baseFunctionTable[aliasTreeName] as any).ev[i]
                                        ? this.Evaluator(tree.args[i], local, fname)
                                        : tree.args[i];
                                }
                                return this.baseFunctionTable[aliasTreeName].func(...argumentsList);
                            }
                        } else if (local && this.localTable[fname] && this.localTable[fname][tree.expr.id]) {
                            /* Defined in localTable **** */
                            return this.localTable[fname][tree.expr.id];
                        } else if (tree.expr.id in this.nameTable) {
                            /* Defined in nameTable */
                            if (this.nameTable[tree.expr.id].args.length === 0) {
                                /* If is a defined name */
                                const temp = this.Evaluator(this.nameTable[tree.expr.id].expr, false, fname);
                                if (tree.args.length === 0) {
                                    /* Defined name */
                                    return temp;
                                } else if (this.isTensor(temp)) {
                                    /* Defined matrix indexing */
                                    for (let i = 0; i < tree.args.length; i++) {
                                        /* Evaluate index list */
                                        argumentsList[i] = this.Evaluator(tree.args[i], local, fname);
                                    }
                                    return this.getItems(temp, tree.expr.id, argumentsList);
                                } else {
                                    throw new Error('invalid matrix indexing or function arguments.');
                                }
                            } else {
                                /* Else is defined function */
                                if (this.nameTable[tree.expr.id].args.length !== tree.args.length) {
                                    throw new Error(`invalid number of arguments in function ${tree.expr.id}.`);
                                }
                                /* Create localTable entry */
                                this.localTable[tree.expr.id] = {};
                                for (let i = 0; i < tree.args.length; i++) {
                                    /* Evaluate defined function arguments list */
                                    this.localTable[tree.expr.id][this.nameTable[tree.expr.id].args[i].id] = this.Evaluator(
                                        tree.args[i],
                                        true,
                                        fname,
                                    );
                                }
                                const temp = this.Evaluator(this.nameTable[tree.expr.id].expr, true, tree.expr.id);
                                /* Delete localTable entry */
                                delete this.localTable[tree.expr.id];
                                return temp;
                            }
                        } else {
                            throw new Error(`'${tree.id}' undefined.`);
                        }
                    } else {
                        /* literal indexing, ex: [1,2;3,4](1,2) */
                        for (let i = 0; i < tree.args.length; i++) {
                            /* Evaluate index list */
                            argumentsList[i] = this.Evaluator(tree.args[i], local, fname);
                        }
                        return this.getItems(tree.expr, '', argumentsList);
                    }
                case 'CmdWList':
                    this.commandWordListTable[tree.id].func(...tree.args.map((word: { str: string }) => word.str));
                    this.exitStatus = Evaluator.response.EXTERNAL;
                    return tree;
                default:
                    throw new Error(`evaluating undefined type '${tree.type}'.`);
            }
        }
    }

    /**
     * Evaluate expression tree.
     * @param tree
     * @returns
     */
    public Evaluate(tree: any): any {
        try {
            this.exitStatus = Evaluator.response.OK;
            return this.Evaluator(tree, false, '');
        } catch (e) {
            this.exitStatus = Evaluator.response.EVAL_ERROR;
            throw e;
        }
    }

    /**
     * Unparse expression tree.
     * @param tree
     * @returns
     */
    public Unparse(tree: any): string {
        try {
            if (tree === undefined) {
                return '';
            }
            if ('list' in tree) {
                let list = '';
                for (let i = 0; i < tree.list.length; i++) {
                    list += this.Unparse(tree.list[i]) + '\n';
                }
                return list;
            } else if (this.isNumber(tree)) {
                /* NUMBER */
                return this.unparseNumber(tree);
            } else if (this.isString(tree)) {
                /* STRING */
                return this.unparseString(tree);
            } else if (this.isTensor(tree)) {
                /* MATRIX */
                return this.unparseTensor(tree, this);
            } else if (this.isRange(tree)) {
                /* RANGE */
                if (tree.start && tree.stop) {
                    if (tree.stride) {
                        return this.Unparse(tree.start) + ':' + this.Unparse(tree.stride) + ':' + this.Unparse(tree.stop);
                    } else {
                        return this.Unparse(tree.start) + ':' + this.Unparse(tree.stop);
                    }
                } else {
                    return ':';
                }
            } else {
                let arglist: string;
                switch (tree.type) {
                    case ':':
                    case '!':
                    case '~':
                        return tree.type;
                    case '+':
                    case '-':
                    case '.*':
                    case '*':
                    case './':
                    case '/':
                    case '.\\':
                    case '\\':
                    case '.^':
                    case '^':
                    case '.**':
                    case '**':
                    case '<':
                    case '<=':
                    case '==':
                    case '>=':
                    case '>':
                    case '!=':
                    case '~=':
                    case '&':
                    case '|':
                    case '&&':
                    case '||':
                    case '=':
                    case '+=':
                    case '-=':
                    case '*=':
                    case '/=':
                    case '\\=':
                    case '^=':
                    case '**=':
                    case '.*=':
                    case './=':
                    case '.\\=':
                    case '.^=':
                    case '.**=':
                    case '&=':
                    case '|=':
                        return this.Unparse(tree.left) + tree.type + this.Unparse(tree.right);
                    case '()':
                        return '(' + this.Unparse(tree.right) + ')';
                    case '!':
                    case '~':
                        return tree.type + this.Unparse(tree.right);
                    case '+_':
                        return '+' + this.Unparse(tree.right);
                    case '-_':
                        return '-' + this.Unparse(tree.right);
                    case '++_':
                        return '++' + this.Unparse(tree.right);
                    case '--_':
                        return '--' + this.Unparse(tree.right);
                    case ".'":
                    case "'":
                        return this.Unparse(tree.left) + tree.type;
                    case '_++':
                        return this.Unparse(tree.left) + '++';
                    case '_--':
                        return this.Unparse(tree.left) + '--';
                    case 'NAME':
                        return tree.id;
                    case 'ARG':
                        arglist = '';
                        for (let i = 0; i < tree.args.length; i++) {
                            arglist += this.Unparse(tree.args[i]) + ',';
                        }
                        return this.Unparse(tree.expr) + '(' + arglist.substring(0, arglist.length - 1) + ')';
                    case 'CmdWList':
                        arglist = '';
                        for (let i = 0; i < tree.args.length; i++) {
                            arglist += this.Unparse(tree.args[i]) + ' ';
                        }
                        return tree.id + arglist.substring(0, arglist.length - 1);
                    default:
                        return '<INVALID>';
                }
            }
        } catch (e) {
            return '<ERROR>';
        }
    }

    /**
     * Unparse recursively expression tree.
     * @param tree Expression tree.
     * @returns String of expression tree unparsed as MathML language.
     */
    private unparserML(tree: any): string {
        try {
            if (tree === undefined) {
                return '';
            }
            if ('list' in tree) {
                let list = '<mtable>';
                for (let i = 0; i < tree.list.length; i++) {
                    list += '<mtr><mtd>' + this.unparserML(tree.list[i]) + '</mtd></mtr>';
                }
                return list + '</mtable>';
            } else if (this.isNumber(tree)) {
                /* NUMBER */
                return this.unparseNumberML(tree);
            } else if (this.isString(tree)) {
                /* STRING */
                return this.unparseStringML(tree);
            } else if (this.isTensor(tree)) {
                /* MATRIX */
                return this.unparseTensorML(tree, this);
            } else if (this.isRange(tree)) {
                /* RANGE */
                if (tree.start && tree.stop) {
                    if (tree.stride) {
                        return this.unparserML(tree.start) + '<mo>:</mo>' + this.unparserML(tree.stride) + '<mo>:</mo>' + this.unparserML(tree.stop);
                    } else {
                        return this.unparserML(tree.start) + '<mo>:</mo>' + this.unparserML(tree.stop);
                    }
                } else {
                    return '<mo>:</mo>';
                }
            } else {
                let arglist: string;
                switch (tree.type) {
                    case ':':
                    case '!':
                    case '~':
                        return '<mo>' + tree.type + '</mo>';
                    case '+':
                    case '-':
                    case '.*':
                    case './':
                    case '.\\':
                    case '\\':
                    case '.^':
                    case '.**':
                    case '<':
                    case '>':
                    case '==':
                    case '&':
                    case '|':
                    case '&&':
                    case '||':
                    case '=':
                    case '+=':
                    case '-=':
                    case '*=':
                    case '/=':
                    case '\\=':
                    case '^=':
                    case '**=':
                    case '.*=':
                    case './=':
                    case '.\\=':
                    case '.^=':
                    case '.**=':
                    case '&=':
                    case '|=':
                        return this.unparserML(tree.left) + '<mo>' + tree.type + '</mo>' + this.unparserML(tree.right);
                    case '<=':
                        return this.unparserML(tree.left) + '<mo>&le;</mo>' + this.unparserML(tree.right);
                    case '>=':
                        return this.unparserML(tree.left) + '<mo>&ge;</mo>' + this.unparserML(tree.right);
                    case '!=':
                    case '~=':
                        return this.unparserML(tree.left) + '<mo>&ne;</mo>' + this.unparserML(tree.right);
                    case '()':
                        return '<mo>(</mo>' + this.unparserML(tree.right) + '<mo>)</mo>';
                    case '*':
                        return this.unparserML(tree.left) + '<mo>&times;</mo>' + this.unparserML(tree.right);
                    case '/':
                        return '<mfrac><mrow>' + this.unparserML(tree.left) + '</mrow><mrow>' + this.unparserML(tree.right) + '</mrow></mfrac>';
                    case '**':
                    case '^':
                        return '<msup><mrow>' + this.unparserML(tree.left) + '</mrow><mrow>' + this.unparserML(tree.right) + '</mrow></msup>';
                    case ':':
                    case '!':
                    case '~':
                        return '<mo>' + tree.type + '</mo>' + this.unparserML(tree.right);
                    case '+_':
                        return '<mo>+</mo>' + this.unparserML(tree.right);
                    case '-_':
                        return '<mo>-</mo>' + this.unparserML(tree.right);
                    case '++_':
                        return '<mo>++</mo>' + this.unparserML(tree.right);
                    case '--_':
                        return '<mo>--</mo>' + this.unparserML(tree.right);
                    case '_++':
                        return this.unparserML(tree.left) + '<mo>++</mo>';
                    case '_--':
                        return this.unparserML(tree.left) + '<mo>--</mo>';
                    case ".'":
                        return '<msup><mrow>' + this.unparserML(tree.left) + '</mrow><mrow><mi>T</mi></mrow></msup>';
                    case "'":
                        return '<msup><mrow>' + this.unparserML(tree.left) + '</mrow><mrow><mi>H</mi></mrow></msup>';
                    case 'NAME':
                        return '<mi>' + substGreek(tree.id) + '</mi>';
                    case 'ARG':
                        if (tree.args.length === 0) {
                            return this.unparserML(tree.expr) + '<mrow><mo>(</mo><mo>)</mo></mrow>';
                        } else {
                            arglist = '';
                            for (let i = 0; i < tree.args.length; i++) {
                                arglist += this.unparserML(tree.args[i]) + '<mo>,</mo>';
                            }
                            arglist = arglist.substring(0, arglist.length - 10);
                            if (tree.expr.type === 'NAME') {
                                const aliasTreeName = this.aliasName(tree.expr.id);
                                switch (aliasTreeName) {
                                    case 'abs':
                                        return '<mrow><mo>|</mo>' + this.unparserML(tree.args[0]) + '<mo>|</mo></mrow>';
                                    case 'conj':
                                        return '<mover><mrow>' + this.unparserML(tree.args[0]) + '</mrow><mo>&OverBar;</mo></mover>';
                                    case 'sqrt':
                                        return '<msqrt><mrow>' + this.unparserML(tree.args[0]) + '</mrow></msqrt>';
                                    case 'root':
                                        return (
                                            '<mroot><mrow>' +
                                            this.unparserML(tree.args[0]) +
                                            '</mrow><mrow>' +
                                            this.unparserML(tree.args[1]) +
                                            '</mrow></mroot>'
                                        );
                                    case 'exp':
                                        return '<msup><mi>e</mi><mrow>' + this.unparserML(tree.args[0]) + '</mrow></msup>';
                                    case 'log':
                                        return (
                                            '<msub><mi>log</mi><mrow>' +
                                            this.unparserML(tree.args[0]) +
                                            '</mrow></msub><mrow>' +
                                            this.unparserML(tree.args[1]) +
                                            '</mrow>'
                                        );
                                    case 'sum':
                                        return (
                                            '<mrow><munderover><mo>&#x2211;</mo><mrow>' +
                                            this.unparserML(tree.args[0]) +
                                            '<mo>=</mo>' +
                                            this.unparserML(tree.args[1]) +
                                            '</mrow>' +
                                            this.unparserML(tree.args[2]) +
                                            '</munderover></mrow>' +
                                            this.unparserML(tree.args[3])
                                        );
                                    case 'prod':
                                        return (
                                            '<mrow><munderover><mo>&#x220F;</mo><mrow>' +
                                            this.unparserML(tree.args[0]) +
                                            '<mo>=</mo>' +
                                            this.unparserML(tree.args[1]) +
                                            '</mrow>' +
                                            this.unparserML(tree.args[2]) +
                                            '</munderover></mrow>' +
                                            this.unparserML(tree.args[3])
                                        );
                                    case 'gamma':
                                        return '<mi>&Gamma;</mi><mrow><mo>(</mo>' + arglist + '<mo>)</mo></mrow>';
                                    case 'factorial':
                                        return '<mrow><mo>(</mo>' + this.unparserML(tree.args[0]) + '<mo>)</mo></mrow><mo>!</mo>';
                                    case 'binomial':
                                        return (
                                            '<mrow><mo>(</mo><mtable><mtr><mtd>' +
                                            this.unparserML(tree.args[0]) +
                                            '</mtd></mtr><mtr><mtd>' +
                                            this.unparserML(tree.args[1]) +
                                            '</mtd></mtr></mtable><mo>)</mo></mrow>'
                                        );
                                    default:
                                        return '<mi>' + substGreek(tree.expr.id) + '</mi><mrow><mo>(</mo>' + arglist + '<mo>)</mo></mrow>';
                                }
                            } else {
                                return this.unparserML(tree.expr) + '<mrow><mo>(</mo>' + arglist + '<mo>)</mo></mrow>';
                            }
                        }
                    case 'CmdWList':
                        arglist = ' ';
                        for (let i = 0; i < tree.args.length; i++) {
                            arglist += this.Unparse(tree.args[i]) + ' ';
                        }
                        return '<mtext>' + tree.id + ' ' + arglist.substring(0, arglist.length - 1) + '</mtext>';
                    default:
                        return '<mi>invalid</mi>';
                }
            }
        } catch (e) {
            if (this.debug) {
                throw e;
            } else {
                return '<mi>error</mi>';
            }
        }
    }

    /**
     * Unparse Expression tree in MathML.
     * @param tree Expression tree.
     * @returns String of expression unparsed as MathML language.
     */
    public UnparseML(tree: any, display: 'inline' | 'block' = 'block'): string {
        let result: string = this.unparserML(tree);
        result = result.replace(/\<mo\>\(\<\/mo\>\<mi\>error\<\/mi\><\mi\>error\<\/mi\>\<mi\>i\<\/mi\>\<mo\>\)\<\/mo\>/gi, '<mi>error</mi>');
        return `<math xmlns = "http://www.w3.org/1998/Math/MathML" display="${display}">${result}</math>`;
    }

    public toMathML(text: string, display: 'inline' | 'block' = 'block'): string {
        return this.UnparseML(this.Parse(text), display);
    }
}
